# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set timestamp and archive/report filenames
        id: vars
        run: |
          echo "ARCHIVE_NAME=Q3_archive_java.txt" >> $GITHUB_OUTPUT

      # Runs a set of commands using the runners shell
      - name: Create archive
        run: |
          cp Q3.java ${{ steps.vars.outputs.RAPPORT_NAME }}
          echo "🗓 Rapport de Martin RAVENEL > ${{ steps.vars.outputs.RAPPORT_NAME }}

      - name: Commit and push archive + report
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add ${{ steps.vars.outputs.ARCHIVE_NAME }}
          git commit -m "📦 Archive générée le ${{ steps.vars.outputs.DATE }}" || echo "Nothing to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
          
